# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirmar_programacion.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.background = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background.sizePolicy().hasHeightForWidth())
        self.background.setSizePolicy(sizePolicy)
        self.background.setStyleSheet("QFrame#background{\n"
"    border-radius: 10px;\n"
"    border: 5px solid rgb(11,11,11);\n"
"}\n"
"QFrame{\n"
"    background-color: rgb(26,26,26);\n"
"    color: rgb(189, 208, 211);\n"
"}")
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.background)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_container = QtWidgets.QFrame(self.background)
        self.title_container.setMaximumSize(QtCore.QSize(16777215, 70))
        self.title_container.setStyleSheet("boder: none;")
        self.title_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_container.setObjectName("title_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.title_container)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title = QtWidgets.QLabel(self.title_container)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.title.setFont(font)
        self.title.setStyleSheet("border: none;")
        self.title.setObjectName("title")
        self.verticalLayout_2.addWidget(self.title)
        self.verticalLayout.addWidget(self.title_container)
        self.body_container = QtWidgets.QFrame(self.background)
        self.body_container.setStyleSheet("border: none;\n"
"border-top: 5px solid rgb(189, 208, 211);\n"
"border-bottom: 5px solid rgb(189, 208, 211);\n"
"border-radius: 0px;")
        self.body_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body_container.setObjectName("body_container")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.body_container)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.body = QtWidgets.QLabel(self.body_container)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.body.setFont(font)
        self.body.setStyleSheet("border: none;")
        self.body.setWordWrap(True)
        self.body.setObjectName("body")
        self.verticalLayout_3.addWidget(self.body)
        self.verticalLayout.addWidget(self.body_container)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.background)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 50))
        self.buttonBox.setStyleSheet("")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_4.addWidget(self.background)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title.setText(_translate("Dialog", "Programar test"))
        self.body.setText(_translate("Dialog", "Estas seguro que quieres programar un test de la marcha para <NOMBRE> con DNI <DNI>"))
