# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'medico.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-color: rgb(26,26,26);\n"
"border: 5px solid rgb(11,11,11);\n"
"border-radius: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.background = QtWidgets.QFrame(self.centralwidget)
        self.background.setStyleSheet("QWidget{\n"
"background-color: rgb(26,26,26);\n"
"border: 5px solid rgb(11,11,11);\n"
"border-radius: 20px;\n"
"}")
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.background)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lateral_bar = QtWidgets.QFrame(self.background)
        self.lateral_bar.setMinimumSize(QtCore.QSize(0, 0))
        self.lateral_bar.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lateral_bar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(31,189,200);\n"
"    border-radius: 16px;\n"
"    color: rgb(189, 208, 211);\n"
"    border: none;\n"
"}\n"
"QLabel{\n"
"    border: none;\n"
"    color: rgb(189, 208, 211);\n"
"}\n"
"QFrame{\n"
"    border-radius: 0px;\n"
"    border:none;\n"
"    background-color: rgb(11,11,11);\n"
"}")
        self.lateral_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lateral_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lateral_bar.setObjectName("lateral_bar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.lateral_bar)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.nombre = QtWidgets.QLabel(self.lateral_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nombre.sizePolicy().hasHeightForWidth())
        self.nombre.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nombre.setFont(font)
        self.nombre.setObjectName("nombre")
        self.verticalLayout_3.addWidget(self.nombre)
        self.medico = QtWidgets.QLabel(self.lateral_bar)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.medico.setFont(font)
        self.medico.setObjectName("medico")
        self.verticalLayout_3.addWidget(self.medico)
        self.centro = QtWidgets.QLabel(self.lateral_bar)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.centro.setFont(font)
        self.centro.setWordWrap(True)
        self.centro.setObjectName("centro")
        self.verticalLayout_3.addWidget(self.centro)
        self.logout = QtWidgets.QPushButton(self.lateral_bar)
        self.logout.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.logout.setFont(font)
        self.logout.setObjectName("logout")
        self.verticalLayout_3.addWidget(self.logout)
        self.exit = QtWidgets.QPushButton(self.lateral_bar)
        self.exit.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.exit.setFont(font)
        self.exit.setObjectName("exit")
        self.verticalLayout_3.addWidget(self.exit)
        self.horizontalLayout_3.addWidget(self.lateral_bar)
        self.main_content = QtWidgets.QFrame(self.background)
        self.main_content.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main_content.setStyleSheet("QFrame{\n"
"    border:none\n"
"}")
        self.main_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_content.setObjectName("main_content")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_content)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.main_content)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toggle_lateral_bar = QtWidgets.QPushButton(self.frame)
        self.toggle_lateral_bar.setStyleSheet("border: none;")
        self.toggle_lateral_bar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/actions/tango-icon-theme-0.8.90/32x32/actions/go-previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggle_lateral_bar.setIcon(icon)
        self.toggle_lateral_bar.setIconSize(QtCore.QSize(32, 32))
        self.toggle_lateral_bar.setObjectName("toggle_lateral_bar")
        self.horizontalLayout_2.addWidget(self.toggle_lateral_bar, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.main_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabla_pacientes = QtWidgets.QTableWidget(self.frame_2)
        self.tabla_pacientes.setStyleSheet("QTableWidget\n"
"{\n"
"    color: rgb(189, 208, 211);\n"
"    border: 1px solid rgb(11,11,11);\n"
"    border-radius: 0px;\n"
"    gridline-color: rgb(11,11,11);\n"
"}\n"
"QTableWidget::item:selected\n"
"{\n"
"    background-color: rgb(11,11,11);\n"
"}\n"
"QHeaderView::section \n"
"{\n"
"    color: rgb(189, 208, 211);\n"
"    background: rgb(11,11,11);\n"
"    font-size: 16px;\n"
"}")
        self.tabla_pacientes.setObjectName("tabla_pacientes")
        self.tabla_pacientes.setColumnCount(5)
        self.tabla_pacientes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_pacientes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_pacientes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_pacientes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_pacientes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_pacientes.setHorizontalHeaderItem(4, item)
        self.verticalLayout_2.addWidget(self.tabla_pacientes, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout_3.addWidget(self.main_content)
        self.horizontalLayout.addWidget(self.background)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nombre.setText(_translate("MainWindow", "Nombre"))
        self.medico.setText(_translate("MainWindow", "Médico"))
        self.centro.setText(_translate("MainWindow", "Nombre centro"))
        self.logout.setText(_translate("MainWindow", "Log out"))
        self.exit.setText(_translate("MainWindow", "Exit"))
        item = self.tabla_pacientes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DNI"))
        item = self.tabla_pacientes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.tabla_pacientes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Centro"))
import resources_rc
