# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mensage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.background = QtWidgets.QFrame(widget)
        self.background.setStyleSheet("QFrame#background{\n"
"    border-radius: 10px;\n"
"    border: 5px solid rgb(11,11,11);\n"
"}\n"
"QFrame{\n"
"    background-color: rgb(26,26,26);\n"
"    color: rgb(189, 208, 211);\n"
"}")
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.background)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.body_container = QtWidgets.QFrame(self.background)
        self.body_container.setStyleSheet("border: none;")
        self.body_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.body_container.setObjectName("body_container")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.body_container)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.body = QtWidgets.QLabel(self.body_container)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.body.setFont(font)
        self.body.setWordWrap(True)
        self.body.setObjectName("body")
        self.verticalLayout_3.addWidget(self.body, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addWidget(self.body_container)
        self.button_container = QtWidgets.QFrame(self.background)
        self.button_container.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_container.setStyleSheet("border: none;")
        self.button_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_container.setObjectName("button_container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.button_container)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button = QtWidgets.QPushButton(self.button_container)
        self.button.setMinimumSize(QtCore.QSize(72, 36))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.button.setFont(font)
        self.button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(31,189,200);\n"
"    border-radius: 16px;\n"
"    color: rgb(189, 208, 211);\n"
"    border: none;\n"
"}")
        self.button.setObjectName("button")
        self.horizontalLayout.addWidget(self.button, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addWidget(self.button_container)
        self.verticalLayout.addWidget(self.background)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.body.setText(_translate("widget", "Se han insertado los datos correctamente"))
        self.button.setText(_translate("widget", "Ok"))
